[package]
name = "voidinstaller"
version = "0.0.0"
authors = ["VoidHub"]
edition = "2021"

[package.metadata.bundle]
name = "VoidInstaller"
identifier = "com.voidhub.installer"

[lib]
name = "voidinstaller_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = "2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true